### ISSUE TITLE
SASS mixin example

### ISSUE THREAD

**Issue by toverux** [dazuaz/responsive-loader#53]
Hello,

First, thanks for this loader, very useful :)

I just wanted to share my solution for integrating this loader with SASS.
SASS users that are using, for example, Bootstrap, can have responsives images very easily, without the boilerplate of the pure-CSS version as showed in the readme:

```scss
@mixin responsive-background-image($url) {
    @each $breakpoint in map-keys($grid-breakpoints) {
        $next-breakpoint: breakpoint-next($breakpoint);

        @include media-breakpoint-up($breakpoint) {
            @if ($next-breakpoint == null) {
                background-image: url('#{$url}?size=3840'); // max: 4k images
            } @else {
                $next-width: map-get($grid-breakpoints, $next-breakpoint);
                background-image: url('#{$url}?size=#{$next-width}');
            }
        }
    }
}
```

Usage:
```scss
@include responsive-background-image('image.jpg');
```

I use it in conjunction with a responsive-loader config that uses Bootstrap breakpoints by default:

```js
options: {
    loader: 'responsive-loader',
    adapter: require('responsive-loader/sharp'),
    sizes: [576, 768, 992, 1200], // copied from Bootstrap breakpoints
```
